kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-ingress-pods
spec:
  podSelector:
    matchLabels:
      app: rsyslog
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: ingress
      ports:
      - protocol: UDP
        port: 10514
