apiVersion: v1
kind: Service
metadata:
  name: syslog-forwarder
spec:
  clusterIP: 172.30.0.100
  ports:
  - port: 10514
    protocol: UDP
    targetPort: 10514
  selector:
    app: syslog-forwarder
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: syslog-receiver
spec:
  clusterIP: 172.30.163.168
  ports:
  - name: syslog-udp
    port: 10514
    protocol: UDP
    targetPort: 10514
  - name: syslog-tcp
    port: 10514
    protocol: TCP
    targetPort: 10514
  selector:
    app: syslog-receiver
  sessionAffinity: None
  type: ClusterIP
